-- Minimal AI Design Studio Schema
--
-- AI-powered design studio with:
-- - AI design tools with multiple models
-- - Design templates with AI integration
-- - Project management with generation tracking
-- - Output variations and quality scoring
-- - Color palettes and style transfers
-- - Usage analytics and ratings

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Drop existing types if they exist
DROP TYPE IF EXISTS ai_tool_type CASCADE;
DROP TYPE IF EXISTS ai_model CASCADE;
DROP TYPE IF EXISTS design_category CASCADE;
DROP TYPE IF EXISTS project_status CASCADE;
DROP TYPE IF EXISTS export_format CASCADE;

-- AI Tool types
CREATE TYPE ai_tool_type AS ENUM (
  'logo',
  'color-palette',
  'style-transfer',
  'image-enhance',
  'auto-layout',
  'background-removal',
  'smart-crop',
  'batch-generate'
);

-- AI Models
CREATE TYPE ai_model AS ENUM (
  'gpt-4-vision',
  'dall-e-3',
  'midjourney-v6',
  'stable-diffusion',
  'ai-upscaler',
  'remove-bg',
  'vision-ai'
);

-- Design categories
CREATE TYPE design_category AS ENUM (
  'logo',
  'branding',
  'social-media',
  'print',
  'web',
  'marketing',
  'illustration',
  'ui-ux'
);

-- Project status
CREATE TYPE project_status AS ENUM (
  'draft',
  'generating',
  'active',
  'review',
  'completed',
  'archived'
);

-- Export formats
CREATE TYPE export_format AS ENUM (
  'svg',
  'png',
  'jpg',
  'pdf',
  'webp'
);

-- ============================================================================
-- TABLES
-- ============================================================================

-- Drop existing tables if they exist
DROP TABLE IF EXISTS tool_reviews CASCADE;
DROP TABLE IF EXISTS project_analytics CASCADE;
DROP TABLE IF EXISTS design_outputs CASCADE;
DROP TABLE IF EXISTS ai_design_projects CASCADE;
DROP TABLE IF EXISTS design_templates CASCADE;
DROP TABLE IF EXISTS ai_tools CASCADE;
DROP TABLE IF EXISTS color_palettes CASCADE;

-- AI Design Projects
CREATE TABLE ai_design_projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type ai_tool_type NOT NULL,
  status project_status NOT NULL DEFAULT 'draft',
  progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  tool_id TEXT NOT NULL,
  template_id TEXT,
  generated_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  model ai_model NOT NULL,
  variations INTEGER NOT NULL DEFAULT 1,
  selected_variation INTEGER,
  prompt TEXT,
  parameters JSONB NOT NULL DEFAULT '{}',
  quality_score DECIMAL(3, 1),
  feedback TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Design Outputs (variations generated by AI)
CREATE TABLE design_outputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES ai_design_projects(id) ON DELETE CASCADE,
  variation_number INTEGER NOT NULL,
  url TEXT NOT NULL,
  thumbnail TEXT NOT NULL,
  format export_format NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  file_size BIGINT NOT NULL,
  quality_score DECIMAL(3, 1) NOT NULL,
  is_selected BOOLEAN NOT NULL DEFAULT false,
  downloads INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(project_id, variation_number)
);

-- Design Templates
CREATE TABLE design_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  category design_category NOT NULL,
  thumbnail TEXT NOT NULL,
  uses INTEGER NOT NULL DEFAULT 0,
  rating DECIMAL(3, 2) DEFAULT 0,
  review_count INTEGER NOT NULL DEFAULT 0,
  ai_ready BOOLEAN NOT NULL DEFAULT false,
  is_premium BOOLEAN NOT NULL DEFAULT false,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- AI Tools
CREATE TABLE ai_tools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type ai_tool_type NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  model ai_model NOT NULL,
  icon TEXT NOT NULL,
  uses INTEGER NOT NULL DEFAULT 0,
  rating DECIMAL(3, 2) DEFAULT 0,
  review_count INTEGER NOT NULL DEFAULT 0,
  is_premium BOOLEAN NOT NULL DEFAULT false,
  estimated_time INTEGER NOT NULL, -- seconds
  max_variations INTEGER NOT NULL DEFAULT 1,
  supported_formats export_format[] DEFAULT ARRAY[]::export_format[],
  features TEXT[] DEFAULT ARRAY[]::TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Color Palettes
CREATE TABLE color_palettes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  colors TEXT[] NOT NULL,
  description TEXT NOT NULL,
  wcag_compliant BOOLEAN NOT NULL DEFAULT false,
  contrast_ratios DECIMAL(4, 2)[] DEFAULT ARRAY[]::DECIMAL(4, 2)[],
  mood TEXT NOT NULL,
  usage TEXT[] DEFAULT ARRAY[]::TEXT[],
  uses INTEGER NOT NULL DEFAULT 0,
  is_public BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Project Analytics
CREATE TABLE project_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES ai_design_projects(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  views INTEGER NOT NULL DEFAULT 0,
  downloads INTEGER NOT NULL DEFAULT 0,
  shares INTEGER NOT NULL DEFAULT 0,
  generation_time INTEGER, -- seconds
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(project_id, date)
);

-- Tool Reviews
CREATE TABLE tool_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id UUID NOT NULL REFERENCES ai_tools(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT NOT NULL,
  helpful INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(tool_id, user_id)
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- ai_design_projects indexes
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_user_id ON ai_design_projects(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_type ON ai_design_projects(type);
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_status ON ai_design_projects(status);
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_model ON ai_design_projects(model);
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_created_at ON ai_design_projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_completed_at ON ai_design_projects(completed_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_design_projects_quality_score ON ai_design_projects(quality_score DESC);

-- design_outputs indexes
CREATE INDEX IF NOT EXISTS idx_design_outputs_project_id ON design_outputs(project_id);
CREATE INDEX IF NOT EXISTS idx_design_outputs_variation_number ON design_outputs(project_id, variation_number);
CREATE INDEX IF NOT EXISTS idx_design_outputs_is_selected ON design_outputs(is_selected);
CREATE INDEX IF NOT EXISTS idx_design_outputs_downloads ON design_outputs(downloads DESC);
CREATE INDEX IF NOT EXISTS idx_design_outputs_quality_score ON design_outputs(quality_score DESC);

-- design_templates indexes
CREATE INDEX IF NOT EXISTS idx_design_templates_category ON design_templates(category);
CREATE INDEX IF NOT EXISTS idx_design_templates_ai_ready ON design_templates(ai_ready);
CREATE INDEX IF NOT EXISTS idx_design_templates_is_premium ON design_templates(is_premium);
CREATE INDEX IF NOT EXISTS idx_design_templates_uses ON design_templates(uses DESC);
CREATE INDEX IF NOT EXISTS idx_design_templates_rating ON design_templates(rating DESC);
CREATE INDEX IF NOT EXISTS idx_design_templates_tags ON design_templates USING gin(tags);

-- ai_tools indexes
CREATE INDEX IF NOT EXISTS idx_ai_tools_type ON ai_tools(type);
CREATE INDEX IF NOT EXISTS idx_ai_tools_model ON ai_tools(model);
CREATE INDEX IF NOT EXISTS idx_ai_tools_is_premium ON ai_tools(is_premium);
CREATE INDEX IF NOT EXISTS idx_ai_tools_uses ON ai_tools(uses DESC);
CREATE INDEX IF NOT EXISTS idx_ai_tools_rating ON ai_tools(rating DESC);

-- color_palettes indexes
CREATE INDEX IF NOT EXISTS idx_color_palettes_user_id ON color_palettes(user_id);
CREATE INDEX IF NOT EXISTS idx_color_palettes_mood ON color_palettes(mood);
CREATE INDEX IF NOT EXISTS idx_color_palettes_wcag_compliant ON color_palettes(wcag_compliant);
CREATE INDEX IF NOT EXISTS idx_color_palettes_is_public ON color_palettes(is_public);
CREATE INDEX IF NOT EXISTS idx_color_palettes_uses ON color_palettes(uses DESC);

-- project_analytics indexes
CREATE INDEX IF NOT EXISTS idx_project_analytics_project_id ON project_analytics(project_id);
CREATE INDEX IF NOT EXISTS idx_project_analytics_date ON project_analytics(date DESC);
CREATE INDEX IF NOT EXISTS idx_project_analytics_project_date ON project_analytics(project_id, date DESC);

-- tool_reviews indexes
CREATE INDEX IF NOT EXISTS idx_tool_reviews_tool_id ON tool_reviews(tool_id);
CREATE INDEX IF NOT EXISTS idx_tool_reviews_user_id ON tool_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_tool_reviews_rating ON tool_reviews(rating DESC);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Auto-update updated_at timestamps
CREATE OR REPLACE FUNCTION update_ai_design_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_ai_design_projects_updated_at
  BEFORE UPDATE ON ai_design_projects
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_design_updated_at();

CREATE TRIGGER trigger_design_templates_updated_at
  BEFORE UPDATE ON design_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_design_updated_at();

CREATE TRIGGER trigger_ai_tools_updated_at
  BEFORE UPDATE ON ai_tools
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_design_updated_at();

CREATE TRIGGER trigger_color_palettes_updated_at
  BEFORE UPDATE ON color_palettes
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_design_updated_at();

CREATE TRIGGER trigger_project_analytics_updated_at
  BEFORE UPDATE ON project_analytics
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_design_updated_at();

CREATE TRIGGER trigger_tool_reviews_updated_at
  BEFORE UPDATE ON tool_reviews
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_design_updated_at();

-- Auto-set completed_at when project status changes to completed
CREATE OR REPLACE FUNCTION update_project_completed_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
    NEW.completed_at = now();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_project_completed_at
  BEFORE UPDATE ON ai_design_projects
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION update_project_completed_at();

-- Increment template uses when used in a project
CREATE OR REPLACE FUNCTION increment_template_uses()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.template_id IS NOT NULL THEN
    UPDATE design_templates
    SET uses = uses + 1
    WHERE id = NEW.template_id::UUID;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_increment_template_uses
  AFTER INSERT ON ai_design_projects
  FOR EACH ROW
  WHEN (NEW.template_id IS NOT NULL)
  EXECUTE FUNCTION increment_template_uses();
