// SESSION_12: GALLERY UTILITIES - World-Class Media Gallery Management
// Production-ready gallery system with comprehensive features

import { createFeatureLogger } from '@/lib/logger'

const logger = createFeatureLogger('Gallery')

// ================================
// TYPESCRIPT INTERFACES
// ================================

export interface GalleryImage {
  id: string
  title: string
  description: string
  fileName: string
  fileSize: number // bytes
  width: number
  height: number
  format: string
  url: string
  thumbnail: string
  uploadDate: string
  modifiedDate?: string
  tags: string[]
  albumId: string | null
  isFavorite: boolean
  type: 'image' | 'video' | 'audio' | 'document'
  category: string
  client?: string
  project?: string
  likes: number
  comments: number
  views: number
  downloads: number
  shares: number
  metadata?: ImageMetadata
  exifData?: ExifData
  colorPalette?: string[]
  aiGenerated?: boolean
  sourcePrompt?: string
  processingStatus?: 'pending' | 'processing' | 'completed' | 'failed'
  userId?: string
  isPublic?: boolean
  shareUrl?: string
}

export interface Album {
  id: string
  name: string
  description: string
  coverImage: string
  imageCount: number
  createdDate: string
  modifiedDate?: string
  totalSize: number
  isPublic: boolean
  shareUrl?: string
  password?: string
  userId?: string
  tags?: string[]
  views?: number
  downloads?: number
}

export interface ImageCollection {
  id: string
  name: string
  description: string
  imageIds: string[]
  createdBy: string
  createdDate: string
  isAutoGenerated?: boolean
  rules?: CollectionRule[]
}

export interface CollectionRule {
  field: string
  operator: 'equals' | 'contains' | 'greater_than' | 'less_than'
  value: string | number
}

export interface ImageMetadata {
  camera?: string
  lens?: string
  iso?: number
  aperture?: string
  shutterSpeed?: string
  focalLength?: string
  location?: string
  coordinates?: { lat: number; lng: number }
  software?: string
  artist?: string
  copyright?: string
  keywords?: string[]
}

export interface ExifData {
  make: string
  model: string
  dateTime: string
  orientation: number
  software: string
  flash?: string
  whiteBalance?: string
  meteringMode?: string
  exposureMode?: string
}

export interface ImageTag {
  id: string
  name: string
  color?: string
  category?: string
  usageCount: number
  createdDate: string
}

export interface ImageComment {
  id: string
  imageId: string
  userId: string
  userName: string
  userAvatar?: string
  text: string
  createdDate: string
  likes: number
  replies?: ImageComment[]
}

export interface ImageShare {
  id: string
  imageId: string
  shareUrl: string
  password?: string
  expiresAt?: string
  permissions: SharePermission[]
  views: number
  downloads: number
  createdDate: string
}

export type SharePermission = 'view' | 'download' | 'comment' | 'edit'

export interface ImageEdit {
  id: string
  imageId: string
  userId: string
  editType: 'crop' | 'resize' | 'filter' | 'adjustment' | 'text' | 'other'
  parameters: Record<string, any>
  createdDate: string
  thumbnail?: string
}

export interface GalleryAnalytics {
  totalImages: number
  totalVideos: number
  totalAlbums: number
  totalStorage: number
  totalViews: number
  totalDownloads: number
  totalLikes: number
  totalComments: number
  topImages: GalleryImage[]
  topAlbums: Album[]
  recentUploads: GalleryImage[]
  storageByCategory: Record<string, number>
  viewsByDay: Array<{ date: string; views: number }>
}

export interface ImageFilter {
  categories?: string[]
  types?: Array<'image' | 'video' | 'audio' | 'document'>
  tags?: string[]
  albumIds?: string[]
  isFavorite?: boolean
  isPublic?: boolean
  aiGenerated?: boolean
  dateRange?: { start: string; end: string }
  minSize?: number
  maxSize?: number
  minDimensions?: { width: number; height: number }
  maxDimensions?: { width: number; height: number }
}

export type SortField = 'date' | 'name' | 'size' | 'type' | 'views' | 'likes' | 'downloads'
export type SortOrder = 'asc' | 'desc'

// ================================
// MOCK DATA - 60+ IMAGES
// ================================

export const mockGalleryImages: GalleryImage[] = [
  // BRANDING CATEGORY (10 images)
  {
    id: 'img-001',
    title: 'Modern Brand Identity',
    description: 'Complete brand identity package with logo variations',
    fileName: 'brand-identity-modern.jpg',
    fileSize: 3145728, // 3 MB
    width: 2400,
    height: 1600,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop',
    uploadDate: '2024-01-15T10:30:00Z',
    tags: ['branding', 'logo', 'identity', 'modern', 'minimalist'],
    albumId: 'album-brand',
    isFavorite: true,
    type: 'image',
    category: 'branding',
    client: 'Tech Innovations Inc',
    project: 'Brand Refresh 2024',
    likes: 45,
    comments: 12,
    views: 328,
    downloads: 23,
    shares: 8,
    colorPalette: ['#1a1a1a', '#ffffff', '#3b82f6', '#8b5cf6'],
    isPublic: true
  },
  {
    id: 'img-002',
    title: 'Corporate Logo Suite',
    description: 'Professional corporate branding with multiple variants',
    fileName: 'corporate-logo-suite.png',
    fileSize: 4194304, // 4 MB
    width: 3000,
    height: 2000,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop',
    uploadDate: '2024-01-14T14:20:00Z',
    tags: ['branding', 'corporate', 'logo', 'professional'],
    albumId: 'album-brand',
    isFavorite: false,
    type: 'image',
    category: 'branding',
    client: 'Global Corp',
    project: 'Corporate Identity',
    likes: 32,
    comments: 8,
    views: 245,
    downloads: 18,
    shares: 5,
    colorPalette: ['#2563eb', '#ffffff', '#1e293b', '#64748b']
  },
  {
    id: 'img-003',
    title: 'Startup Brand Package',
    description: 'Fresh startup branding with vibrant colors',
    fileName: 'startup-brand.svg',
    fileSize: 524288, // 512 KB
    width: 1920,
    height: 1080,
    format: 'svg',
    url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop',
    uploadDate: '2024-01-13T09:15:00Z',
    tags: ['branding', 'startup', 'colorful', 'modern'],
    albumId: 'album-brand',
    isFavorite: true,
    type: 'image',
    category: 'branding',
    client: 'InnovateLab',
    project: 'Brand Launch',
    likes: 67,
    comments: 15,
    views: 412,
    downloads: 34,
    shares: 12,
    colorPalette: ['#f59e0b', '#8b5cf6', '#ffffff', '#1f2937']
  },
  {
    id: 'img-004',
    title: 'Minimalist Logo Design',
    description: 'Clean and simple logo design for tech company',
    fileName: 'minimalist-logo.png',
    fileSize: 1048576, // 1 MB
    width: 2000,
    height: 2000,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=300&fit=crop',
    uploadDate: '2024-01-12T16:45:00Z',
    tags: ['logo', 'minimalist', 'tech', 'simple'],
    albumId: 'album-brand',
    isFavorite: false,
    type: 'image',
    category: 'branding',
    likes: 28,
    comments: 6,
    views: 189,
    downloads: 15,
    shares: 4,
    colorPalette: ['#000000', '#ffffff']
  },
  {
    id: 'img-005',
    title: 'Vintage Brand Identity',
    description: 'Retro-inspired branding for artisanal coffee shop',
    fileName: 'vintage-brand.jpg',
    fileSize: 2621440, // 2.5 MB
    width: 2200,
    height: 1650,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=400&h=300&fit=crop',
    uploadDate: '2024-01-11T11:30:00Z',
    tags: ['branding', 'vintage', 'retro', 'coffee'],
    albumId: 'album-brand',
    isFavorite: true,
    type: 'image',
    category: 'branding',
    client: 'Brew & Co',
    project: 'Coffee Shop Branding',
    likes: 53,
    comments: 11,
    views: 298,
    downloads: 27,
    shares: 9,
    colorPalette: ['#92400e', '#fef3c7', '#1f2937', '#d97706']
  },
  {
    id: 'img-006',
    title: 'Fashion Brand Logo',
    description: 'Elegant logo design for luxury fashion brand',
    fileName: 'fashion-logo.png',
    fileSize: 1572864, // 1.5 MB
    width: 1800,
    height: 1800,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&h=300&fit=crop',
    uploadDate: '2024-01-10T08:20:00Z',
    tags: ['fashion', 'luxury', 'elegant', 'logo'],
    albumId: 'album-brand',
    isFavorite: false,
    type: 'image',
    category: 'branding',
    client: 'Élégance Couture',
    likes: 41,
    comments: 9,
    views: 267,
    downloads: 21,
    shares: 7,
    colorPalette: ['#1f2937', '#f3f4f6', '#d4af37']
  },
  {
    id: 'img-007',
    title: 'Sports Brand Identity',
    description: 'Dynamic branding for athletic wear company',
    fileName: 'sports-brand.jpg',
    fileSize: 3670016, // 3.5 MB
    width: 2560,
    height: 1440,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&h=300&fit=crop',
    uploadDate: '2024-01-09T15:10:00Z',
    tags: ['sports', 'athletic', 'dynamic', 'branding'],
    albumId: 'album-brand',
    isFavorite: true,
    type: 'image',
    category: 'branding',
    client: 'FitForce',
    project: 'Athletic Wear Branding',
    likes: 59,
    comments: 13,
    views: 387,
    downloads: 31,
    shares: 10,
    colorPalette: ['#ef4444', '#1f2937', '#ffffff', '#fbbf24']
  },
  {
    id: 'img-008',
    title: 'Eco-Friendly Brand',
    description: 'Sustainable brand identity with natural elements',
    fileName: 'eco-brand.png',
    fileSize: 2097152, // 2 MB
    width: 2100,
    height: 1400,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=300&fit=crop',
    uploadDate: '2024-01-08T12:45:00Z',
    tags: ['eco', 'sustainable', 'nature', 'green'],
    albumId: 'album-brand',
    isFavorite: false,
    type: 'image',
    category: 'branding',
    client: 'GreenLeaf Co',
    likes: 38,
    comments: 7,
    views: 223,
    downloads: 19,
    shares: 6,
    colorPalette: ['#10b981', '#065f46', '#fef3c7', '#1f2937']
  },
  {
    id: 'img-009',
    title: 'Tech Startup Logo',
    description: 'Futuristic logo for AI technology startup',
    fileName: 'tech-startup-logo.svg',
    fileSize: 327680, // 320 KB
    width: 1600,
    height: 1600,
    format: 'svg',
    url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop',
    uploadDate: '2024-01-07T09:30:00Z',
    tags: ['tech', 'AI', 'futuristic', 'startup'],
    albumId: 'album-brand',
    isFavorite: true,
    type: 'image',
    category: 'branding',
    client: 'NeuralNet Labs',
    project: 'AI Startup Branding',
    likes: 72,
    comments: 16,
    views: 456,
    downloads: 38,
    shares: 14,
    colorPalette: ['#6366f1', '#8b5cf6', '#1f2937', '#ffffff']
  },
  {
    id: 'img-010',
    title: 'Restaurant Brand Package',
    description: 'Complete branding for upscale restaurant',
    fileName: 'restaurant-brand.jpg',
    fileSize: 2883584, // 2.75 MB
    width: 2300,
    height: 1533,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    uploadDate: '2024-01-06T17:20:00Z',
    tags: ['restaurant', 'food', 'upscale', 'branding'],
    albumId: 'album-brand',
    isFavorite: false,
    type: 'image',
    category: 'branding',
    client: 'La Maison',
    likes: 44,
    comments: 10,
    views: 312,
    downloads: 25,
    shares: 8,
    colorPalette: ['#7c2d12', '#fef3c7', '#1f2937', '#f59e0b']
  },

  // WEB DESIGN CATEGORY (10 images)
  {
    id: 'img-011',
    title: 'E-commerce Landing Page',
    description: 'Modern e-commerce website design with clean UI',
    fileName: 'ecommerce-landing.png',
    fileSize: 5242880, // 5 MB
    width: 3840,
    height: 2160,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    uploadDate: '2024-01-15T11:00:00Z',
    tags: ['web-design', 'ecommerce', 'landing-page', 'UI'],
    albumId: 'album-web',
    isFavorite: true,
    type: 'image',
    category: 'web-design',
    client: 'ShopifyPlus',
    project: 'E-commerce Redesign',
    likes: 89,
    comments: 21,
    views: 567,
    downloads: 42,
    shares: 18,
    colorPalette: ['#3b82f6', '#ffffff', '#1f2937', '#f3f4f6']
  },
  {
    id: 'img-012',
    title: 'SaaS Dashboard UI',
    description: 'Professional dashboard interface for SaaS application',
    fileName: 'saas-dashboard.png',
    fileSize: 4718592, // 4.5 MB
    width: 3200,
    height: 1800,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
    uploadDate: '2024-01-14T13:45:00Z',
    tags: ['web-design', 'SaaS', 'dashboard', 'analytics'],
    albumId: 'album-web',
    isFavorite: true,
    type: 'image',
    category: 'web-design',
    client: 'DataMetrics',
    likes: 76,
    comments: 18,
    views: 489,
    downloads: 36,
    shares: 15,
    colorPalette: ['#8b5cf6', '#ffffff', '#1e293b', '#06b6d4']
  },
  {
    id: 'img-013',
    title: 'Portfolio Website',
    description: 'Creative portfolio design for photographer',
    fileName: 'portfolio-website.jpg',
    fileSize: 3932160, // 3.75 MB
    width: 2880,
    height: 1620,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=400&h=300&fit=crop',
    uploadDate: '2024-01-13T10:30:00Z',
    tags: ['web-design', 'portfolio', 'photography', 'creative'],
    albumId: 'album-web',
    isFavorite: false,
    type: 'image',
    category: 'web-design',
    client: 'Emma Photography',
    likes: 63,
    comments: 14,
    views: 401,
    downloads: 29,
    shares: 11,
    colorPalette: ['#000000', '#ffffff', '#f59e0b']
  },
  {
    id: 'img-014',
    title: 'Corporate Website Redesign',
    description: 'Enterprise website with modern layout',
    fileName: 'corporate-website.png',
    fileSize: 5767168, // 5.5 MB
    width: 3000,
    height: 2000,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=400&h=300&fit=crop',
    uploadDate: '2024-01-12T15:20:00Z',
    tags: ['web-design', 'corporate', 'enterprise', 'modern'],
    albumId: 'album-web',
    isFavorite: false,
    type: 'image',
    category: 'web-design',
    client: 'Fortune 500 Co',
    likes: 54,
    comments: 12,
    views: 378,
    downloads: 27,
    shares: 9,
    colorPalette: ['#1e40af', '#ffffff', '#64748b', '#f1f5f9']
  },
  {
    id: 'img-015',
    title: 'Mobile App Landing',
    description: 'Landing page for mobile application launch',
    fileName: 'mobile-app-landing.jpg',
    fileSize: 3407872, // 3.25 MB
    width: 2560,
    height: 1440,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop',
    uploadDate: '2024-01-11T09:15:00Z',
    tags: ['web-design', 'mobile-app', 'landing-page', 'launch'],
    albumId: 'album-web',
    isFavorite: true,
    type: 'image',
    category: 'web-design',
    client: 'TaskMaster App',
    project: 'App Launch Campaign',
    likes: 81,
    comments: 19,
    views: 523,
    downloads: 39,
    shares: 16,
    colorPalette: ['#ec4899', '#8b5cf6', '#ffffff', '#1f2937']
  },
  {
    id: 'img-016',
    title: 'Blog Homepage Design',
    description: 'Clean blog layout with featured articles',
    fileName: 'blog-homepage.png',
    fileSize: 2621440, // 2.5 MB
    width: 2200,
    height: 1650,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&h=300&fit=crop',
    uploadDate: '2024-01-10T14:40:00Z',
    tags: ['web-design', 'blog', 'content', 'clean'],
    albumId: 'album-web',
    isFavorite: false,
    type: 'image',
    category: 'web-design',
    likes: 47,
    comments: 10,
    views: 289,
    downloads: 22,
    shares: 7,
    colorPalette: ['#ffffff', '#1f2937', '#3b82f6', '#f3f4f6']
  },
  {
    id: 'img-017',
    title: 'Startup Homepage',
    description: 'Bold startup website with hero section',
    fileName: 'startup-homepage.jpg',
    fileSize: 4456448, // 4.25 MB
    width: 3400,
    height: 1912,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop',
    uploadDate: '2024-01-09T11:25:00Z',
    tags: ['web-design', 'startup', 'hero', 'bold'],
    albumId: 'album-web',
    isFavorite: true,
    type: 'image',
    category: 'web-design',
    client: 'RocketLaunch',
    likes: 94,
    comments: 22,
    views: 612,
    downloads: 47,
    shares: 20,
    colorPalette: ['#10b981', '#1f2937', '#ffffff', '#fbbf24']
  },
  {
    id: 'img-018',
    title: 'Real Estate Platform',
    description: 'Property listing website design',
    fileName: 'real-estate-platform.png',
    fileSize: 5505024, // 5.25 MB
    width: 3600,
    height: 2025,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop',
    uploadDate: '2024-01-08T16:50:00Z',
    tags: ['web-design', 'real-estate', 'property', 'listing'],
    albumId: 'album-web',
    isFavorite: false,
    type: 'image',
    category: 'web-design',
    client: 'HomeFinderPro',
    likes: 58,
    comments: 13,
    views: 367,
    downloads: 28,
    shares: 10,
    colorPalette: ['#0f766e', '#ffffff', '#1f2937', '#fcd34d']
  },
  {
    id: 'img-019',
    title: 'Education Portal',
    description: 'E-learning platform interface design',
    fileName: 'education-portal.jpg',
    fileSize: 3670016, // 3.5 MB
    width: 2800,
    height: 1575,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400&h=300&fit=crop',
    uploadDate: '2024-01-07T13:15:00Z',
    tags: ['web-design', 'education', 'e-learning', 'portal'],
    albumId: 'album-web',
    isFavorite: true,
    type: 'image',
    category: 'web-design',
    client: 'EduLearn',
    project: 'Learning Platform',
    likes: 69,
    comments: 16,
    views: 445,
    downloads: 34,
    shares: 13,
    colorPalette: ['#7c3aed', '#ffffff', '#1f2937', '#06b6d4']
  },
  {
    id: 'img-020',
    title: 'Health App Interface',
    description: 'Wellness tracking app web interface',
    fileName: 'health-app-interface.png',
    fileSize: 3145728, // 3 MB
    width: 2400,
    height: 1350,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop',
    uploadDate: '2024-01-06T10:05:00Z',
    tags: ['web-design', 'health', 'wellness', 'app'],
    albumId: 'album-web',
    isFavorite: false,
    type: 'image',
    category: 'web-design',
    client: 'WellnessTrack',
    likes: 52,
    comments: 11,
    views: 334,
    downloads: 26,
    shares: 8,
    colorPalette: ['#059669', '#ffffff', '#1e293b', '#fbbf24']
  },

  // MOBILE CATEGORY (8 images)
  {
    id: 'img-021',
    title: 'iOS Banking App',
    description: 'Mobile banking app interface design',
    fileName: 'ios-banking-app.png',
    fileSize: 2097152, // 2 MB
    width: 1170,
    height: 2532,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=200&h=400&fit=crop',
    uploadDate: '2024-01-15T09:30:00Z',
    tags: ['mobile', 'iOS', 'banking', 'fintech'],
    albumId: 'album-mobile',
    isFavorite: true,
    type: 'image',
    category: 'mobile',
    client: 'BankTech',
    project: 'Mobile Banking App',
    likes: 103,
    comments: 25,
    views: 678,
    downloads: 51,
    shares: 22,
    colorPalette: ['#1e3a8a', '#ffffff', '#3b82f6', '#f3f4f6']
  },
  {
    id: 'img-022',
    title: 'Fitness Tracker UI',
    description: 'Workout tracking mobile application',
    fileName: 'fitness-tracker.png',
    fileSize: 1835008, // 1.75 MB
    width: 1080,
    height: 2340,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=200&h=400&fit=crop',
    uploadDate: '2024-01-14T11:20:00Z',
    tags: ['mobile', 'fitness', 'health', 'tracker'],
    albumId: 'album-mobile',
    isFavorite: true,
    type: 'image',
    category: 'mobile',
    client: 'FitLife',
    likes: 87,
    comments: 20,
    views: 556,
    downloads: 43,
    shares: 18,
    colorPalette: ['#dc2626', '#ffffff', '#1f2937', '#fbbf24']
  },
  {
    id: 'img-023',
    title: 'Food Delivery App',
    description: 'Restaurant ordering mobile app',
    fileName: 'food-delivery-app.jpg',
    fileSize: 2359296, // 2.25 MB
    width: 1125,
    height: 2436,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&h=400&fit=crop',
    uploadDate: '2024-01-13T14:45:00Z',
    tags: ['mobile', 'food', 'delivery', 'restaurant'],
    albumId: 'album-mobile',
    isFavorite: false,
    type: 'image',
    category: 'mobile',
    client: 'QuickBite',
    likes: 72,
    comments: 17,
    views: 467,
    downloads: 36,
    shares: 14,
    colorPalette: ['#f59e0b', '#1f2937', '#ffffff', '#ef4444']
  },
  {
    id: 'img-024',
    title: 'Travel Booking App',
    description: 'Flight and hotel booking mobile interface',
    fileName: 'travel-booking.png',
    fileSize: 2621440, // 2.5 MB
    width: 1242,
    height: 2688,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=200&h=400&fit=crop',
    uploadDate: '2024-01-12T10:15:00Z',
    tags: ['mobile', 'travel', 'booking', 'vacation'],
    albumId: 'album-mobile',
    isFavorite: true,
    type: 'image',
    category: 'mobile',
    client: 'WanderWays',
    project: 'Travel App Redesign',
    likes: 95,
    comments: 23,
    views: 612,
    downloads: 48,
    shares: 19,
    colorPalette: ['#06b6d4', '#ffffff', '#1e293b', '#8b5cf6']
  },
  {
    id: 'img-025',
    title: 'Music Streaming UI',
    description: 'Music player mobile application',
    fileName: 'music-streaming.jpg',
    fileSize: 1572864, // 1.5 MB
    width: 1080,
    height: 2400,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=400&fit=crop',
    uploadDate: '2024-01-11T16:30:00Z',
    tags: ['mobile', 'music', 'streaming', 'audio'],
    albumId: 'album-mobile',
    isFavorite: false,
    type: 'image',
    category: 'mobile',
    client: 'SoundWave',
    likes: 64,
    comments: 15,
    views: 423,
    downloads: 32,
    shares: 12,
    colorPalette: ['#8b5cf6', '#1f2937', '#ffffff', '#ec4899']
  },
  {
    id: 'img-026',
    title: 'Social Media App',
    description: 'Social networking mobile interface',
    fileName: 'social-media-app.png',
    fileSize: 2883584, // 2.75 MB
    width: 1170,
    height: 2532,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&h=400&fit=crop',
    uploadDate: '2024-01-10T13:20:00Z',
    tags: ['mobile', 'social', 'networking', 'community'],
    albumId: 'album-mobile',
    isFavorite: true,
    type: 'image',
    category: 'mobile',
    client: 'ConnectHub',
    likes: 118,
    comments: 28,
    views: 789,
    downloads: 62,
    shares: 26,
    colorPalette: ['#3b82f6', '#ffffff', '#1e293b', '#10b981']
  },
  {
    id: 'img-027',
    title: 'E-reader App Interface',
    description: 'Digital reading application design',
    fileName: 'ereader-app.jpg',
    fileSize: 1310720, // 1.25 MB
    width: 1080,
    height: 2340,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=200&h=400&fit=crop',
    uploadDate: '2024-01-09T09:45:00Z',
    tags: ['mobile', 'reading', 'books', 'ereader'],
    albumId: 'album-mobile',
    isFavorite: false,
    type: 'image',
    category: 'mobile',
    client: 'BookWorm',
    likes: 56,
    comments: 13,
    views: 367,
    downloads: 28,
    shares: 10,
    colorPalette: ['#fef3c7', '#92400e', '#1f2937', '#ffffff']
  },
  {
    id: 'img-028',
    title: 'Weather App UI',
    description: 'Modern weather forecast application',
    fileName: 'weather-app.png',
    fileSize: 2097152, // 2 MB
    width: 1125,
    height: 2436,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1561484930-998b6a7b22e8?w=400&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1561484930-998b6a7b22e8?w=200&h=400&fit=crop',
    uploadDate: '2024-01-08T15:10:00Z',
    tags: ['mobile', 'weather', 'forecast', 'UI'],
    albumId: 'album-mobile',
    isFavorite: true,
    type: 'image',
    category: 'mobile',
    client: 'WeatherPro',
    likes: 81,
    comments: 19,
    views: 523,
    downloads: 40,
    shares: 16,
    colorPalette: ['#0284c7', '#ffffff', '#1e293b', '#fbbf24']
  },

  // SOCIAL MEDIA CATEGORY (8 images)
  {
    id: 'img-029',
    title: 'Instagram Campaign Graphics',
    description: 'Social media campaign for product launch',
    fileName: 'instagram-campaign.jpg',
    fileSize: 1835008, // 1.75 MB
    width: 1080,
    height: 1080,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=300&h=300&fit=crop',
    uploadDate: '2024-01-15T12:00:00Z',
    tags: ['social', 'instagram', 'campaign', 'product-launch'],
    albumId: 'album-social',
    isFavorite: true,
    type: 'image',
    category: 'social',
    client: 'BeautyBrand',
    project: 'Product Launch Campaign',
    likes: 156,
    comments: 34,
    views: 1023,
    downloads: 78,
    shares: 45,
    colorPalette: ['#ec4899', '#ffffff', '#fbbf24', '#1f2937']
  },
  {
    id: 'img-030',
    title: 'LinkedIn Banner Design',
    description: 'Professional LinkedIn company banner',
    fileName: 'linkedin-banner.png',
    fileSize: 1048576, // 1 MB
    width: 1584,
    height: 396,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=200&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=100&fit=crop',
    uploadDate: '2024-01-14T10:30:00Z',
    tags: ['social', 'linkedin', 'banner', 'corporate'],
    albumId: 'album-social',
    isFavorite: false,
    type: 'image',
    category: 'social',
    client: 'TechCorp',
    likes: 67,
    comments: 15,
    views: 445,
    downloads: 34,
    shares: 12,
    colorPalette: ['#0a66c2', '#ffffff', '#1f2937', '#64748b']
  },
  {
    id: 'img-031',
    title: 'Facebook Ad Creative',
    description: 'Eye-catching Facebook advertisement design',
    fileName: 'facebook-ad.jpg',
    fileSize: 2097152, // 2 MB
    width: 1200,
    height: 628,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=400&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=200&fit=crop',
    uploadDate: '2024-01-13T15:45:00Z',
    tags: ['social', 'facebook', 'ad', 'marketing'],
    albumId: 'album-social',
    isFavorite: true,
    type: 'image',
    category: 'social',
    client: 'MarketPro',
    project: 'Q1 Ad Campaign',
    likes: 92,
    comments: 21,
    views: 612,
    downloads: 47,
    shares: 28,
    colorPalette: ['#1877f2', '#ffffff', '#10b981', '#1f2937']
  },
  {
    id: 'img-032',
    title: 'Twitter Header Image',
    description: 'Professional Twitter profile header',
    fileName: 'twitter-header.png',
    fileSize: 786432, // 768 KB
    width: 1500,
    height: 500,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=267&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=133&fit=crop',
    uploadDate: '2024-01-12T09:20:00Z',
    tags: ['social', 'twitter', 'header', 'profile'],
    albumId: 'album-social',
    isFavorite: false,
    type: 'image',
    category: 'social',
    client: 'Personal Brand',
    likes: 54,
    comments: 12,
    views: 356,
    downloads: 27,
    shares: 9,
    colorPalette: ['#1da1f2', '#ffffff', '#1f2937', '#8b5cf6']
  },
  {
    id: 'img-033',
    title: 'Pinterest Pin Graphics',
    description: 'Vertical pin graphics for Pinterest marketing',
    fileName: 'pinterest-pins.jpg',
    fileSize: 1572864, // 1.5 MB
    width: 1000,
    height: 1500,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=200&h=300&fit=crop',
    uploadDate: '2024-01-11T14:15:00Z',
    tags: ['social', 'pinterest', 'pin', 'marketing'],
    albumId: 'album-social',
    isFavorite: true,
    type: 'image',
    category: 'social',
    client: 'DIY Blog',
    likes: 73,
    comments: 17,
    views: 478,
    downloads: 36,
    shares: 21,
    colorPalette: ['#e60023', '#ffffff', '#fbbf24', '#1f2937']
  },
  {
    id: 'img-034',
    title: 'TikTok Video Thumbnail',
    description: 'Engaging thumbnail for TikTok video',
    fileName: 'tiktok-thumbnail.png',
    fileSize: 1310720, // 1.25 MB
    width: 1080,
    height: 1920,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&h=700&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=200&h=350&fit=crop',
    uploadDate: '2024-01-10T11:40:00Z',
    tags: ['social', 'tiktok', 'video', 'thumbnail'],
    albumId: 'album-social',
    isFavorite: false,
    type: 'image',
    category: 'social',
    client: 'Creator Studio',
    likes: 88,
    comments: 20,
    views: 567,
    downloads: 43,
    shares: 31,
    colorPalette: ['#69c9d0', '#ee1d52', '#ffffff', '#1f2937']
  },
  {
    id: 'img-035',
    title: 'YouTube Channel Art',
    description: 'Custom YouTube channel banner design',
    fileName: 'youtube-banner.jpg',
    fileSize: 1835008, // 1.75 MB
    width: 2560,
    height: 1440,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=800&h=450&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&h=225&fit=crop',
    uploadDate: '2024-01-09T16:25:00Z',
    tags: ['social', 'youtube', 'banner', 'channel'],
    albumId: 'album-social',
    isFavorite: true,
    type: 'image',
    category: 'social',
    client: 'TechReview Channel',
    project: 'Channel Rebrand',
    likes: 105,
    comments: 24,
    views: 689,
    downloads: 53,
    shares: 19,
    colorPalette: ['#ff0000', '#ffffff', '#1f2937', '#282828']
  },
  {
    id: 'img-036',
    title: 'Story Templates Set',
    description: 'Instagram and Facebook story templates',
    fileName: 'story-templates.png',
    fileSize: 2359296, // 2.25 MB
    width: 1080,
    height: 1920,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=400&h=700&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=200&h=350&fit=crop',
    uploadDate: '2024-01-08T13:50:00Z',
    tags: ['social', 'stories', 'templates', 'instagram'],
    albumId: 'album-social',
    isFavorite: true,
    type: 'image',
    category: 'social',
    client: 'Social Media Agency',
    likes: 127,
    comments: 29,
    views: 834,
    downloads: 64,
    shares: 38,
    colorPalette: ['#8b5cf6', '#ec4899', '#ffffff', '#1f2937']
  },

  // PRINT CATEGORY (6 images)
  {
    id: 'img-037',
    title: 'Business Card Design',
    description: 'Professional business card with modern layout',
    fileName: 'business-card.pdf',
    fileSize: 2097152, // 2 MB
    width: 3.5,
    height: 2,
    format: 'pdf',
    url: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?w=600&h=400&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?w=300&h=200&fit=crop',
    uploadDate: '2024-01-15T08:45:00Z',
    tags: ['print', 'business-card', 'professional', 'corporate'],
    albumId: 'album-print',
    isFavorite: true,
    type: 'document',
    category: 'print',
    client: 'Executive Solutions',
    likes: 63,
    comments: 14,
    views: 412,
    downloads: 31,
    shares: 11,
    colorPalette: ['#1f2937', '#f3f4f6', '#3b82f6']
  },
  {
    id: 'img-038',
    title: 'Brochure Layout',
    description: 'Tri-fold brochure for corporate services',
    fileName: 'corporate-brochure.pdf',
    fileSize: 5242880, // 5 MB
    width: 11,
    height: 8.5,
    format: 'pdf',
    url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop',
    uploadDate: '2024-01-14T12:30:00Z',
    tags: ['print', 'brochure', 'tri-fold', 'corporate'],
    albumId: 'album-print',
    isFavorite: false,
    type: 'document',
    category: 'print',
    client: 'Corporate Services Inc',
    project: 'Marketing Materials',
    likes: 47,
    comments: 10,
    views: 289,
    downloads: 22,
    shares: 7,
    colorPalette: ['#1e40af', '#ffffff', '#64748b', '#f1f5f9']
  },
  {
    id: 'img-039',
    title: 'Event Poster',
    description: 'Large format poster for music festival',
    fileName: 'music-festival-poster.jpg',
    fileSize: 8388608, // 8 MB
    width: 24,
    height: 36,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&h=900&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&h=450&fit=crop',
    uploadDate: '2024-01-13T16:20:00Z',
    tags: ['print', 'poster', 'event', 'festival'],
    albumId: 'album-print',
    isFavorite: true,
    type: 'image',
    category: 'print',
    client: 'Summer Beats Festival',
    likes: 94,
    comments: 22,
    views: 612,
    downloads: 47,
    shares: 23,
    colorPalette: ['#ec4899', '#8b5cf6', '#fbbf24', '#1f2937']
  },
  {
    id: 'img-040',
    title: 'Magazine Spread',
    description: 'Double-page magazine layout design',
    fileName: 'magazine-spread.pdf',
    fileSize: 6291456, // 6 MB
    width: 16,
    height: 11,
    format: 'pdf',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=550&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=275&fit=crop',
    uploadDate: '2024-01-12 08:15:00Z',
    tags: ['print', 'magazine', 'editorial', 'layout'],
    albumId: 'album-print',
    isFavorite: false,
    type: 'document',
    category: 'print',
    client: 'Lifestyle Magazine',
    likes: 56,
    comments: 13,
    views: 367,
    downloads: 28,
    shares: 9,
    colorPalette: ['#ffffff', '#1f2937', '#ef4444', '#f3f4f6']
  },
  {
    id: 'img-041',
    title: 'Product Packaging',
    description: 'Premium product box packaging design',
    fileName: 'product-packaging.jpg',
    fileSize: 4718592, // 4.5 MB
    width: 3000,
    height: 2000,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1561052967-61fc91e48d79?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1561052967-61fc91e48d79?w=400&h=300&fit=crop',
    uploadDate: '2024-01-11T13:40:00Z',
    tags: ['print', 'packaging', 'product', 'premium'],
    albumId: 'album-print',
    isFavorite: true,
    type: 'image',
    category: 'print',
    client: 'Luxury Goods Co',
    project: 'Product Line Packaging',
    likes: 82,
    comments: 19,
    views: 534,
    downloads: 41,
    shares: 16,
    colorPalette: ['#7c2d12', '#fef3c7', '#1f2937', '#d97706']
  },
  {
    id: 'img-042',
    title: 'Flyer Design',
    description: 'Promotional flyer for grand opening',
    fileName: 'grand-opening-flyer.pdf',
    fileSize: 3145728, // 3 MB
    width: 8.5,
    height: 11,
    format: 'pdf',
    url: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=300&h=400&fit=crop',
    uploadDate: '2024-01-10T10:25:00Z',
    tags: ['print', 'flyer', 'promotional', 'event'],
    albumId: 'album-print',
    isFavorite: false,
    type: 'document',
    category: 'print',
    client: 'New Restaurant',
    likes: 39,
    comments: 8,
    views: 245,
    downloads: 19,
    shares: 6,
    colorPalette: ['#dc2626', '#fbbf24', '#ffffff', '#1f2937']
  },

  // VIDEO CATEGORY (6 images/videos)
  {
    id: 'img-043',
    title: 'Product Demo Video',
    description: 'High-quality product demonstration video',
    fileName: 'product-demo.mp4',
    fileSize: 52428800, // 50 MB
    width: 1920,
    height: 1080,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    uploadDate: '2024-01-15T14:00:00Z',
    tags: ['video', 'product', 'demo', 'commercial'],
    albumId: 'album-video',
    isFavorite: true,
    type: 'video',
    category: 'video',
    client: 'TechGadgets',
    project: 'Product Launch Video',
    likes: 142,
    comments: 31,
    views: 2345,
    downloads: 89,
    shares: 54,
    colorPalette: ['#3b82f6', '#ffffff', '#1f2937']
  },
  {
    id: 'img-044',
    title: 'Corporate Presentation',
    description: 'Company overview presentation video',
    fileName: 'corporate-presentation.mp4',
    fileSize: 73400320, // 70 MB
    width: 1920,
    height: 1080,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=300&fit=crop',
    uploadDate: '2024-01-14T09:30:00Z',
    tags: ['video', 'corporate', 'presentation', 'business'],
    albumId: 'album-video',
    isFavorite: false,
    type: 'video',
    category: 'video',
    client: 'Global Enterprises',
    likes: 78,
    comments: 17,
    views: 1234,
    downloads: 56,
    shares: 23,
    colorPalette: ['#1e40af', '#64748b', '#ffffff']
  },
  {
    id: 'img-045',
    title: 'Social Media Ad Video',
    description: '15-second promotional video for Instagram',
    fileName: 'instagram-ad-video.mp4',
    fileSize: 20971520, // 20 MB
    width: 1080,
    height: 1920,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=700&fit=crop',
    uploadDate: '2024-01-13T11:45:00Z',
    tags: ['video', 'social-media', 'ad', 'instagram'],
    albumId: 'album-video',
    isFavorite: true,
    type: 'video',
    category: 'video',
    client: 'Fashion Brand',
    project: 'Social Campaign Q1',
    likes: 167,
    comments: 38,
    views: 3456,
    downloads: 102,
    shares: 78,
    colorPalette: ['#ec4899', '#8b5cf6', '#ffffff']
  },
  {
    id: 'img-046',
    title: 'Tutorial Video',
    description: 'How-to tutorial for software product',
    fileName: 'software-tutorial.mp4',
    fileSize: 41943040, // 40 MB
    width: 1280,
    height: 720,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=400&h=300&fit=crop',
    uploadDate: '2024-01-12T15:20:00Z',
    tags: ['video', 'tutorial', 'education', 'software'],
    albumId: 'album-video',
    isFavorite: false,
    type: 'video',
    category: 'video',
    client: 'SoftwareHelp',
    likes: 93,
    comments: 21,
    views: 1567,
    downloads: 67,
    shares: 34,
    colorPalette: ['#10b981', '#1f2937', '#ffffff']
  },
  {
    id: 'img-047',
    title: 'Event Highlight Reel',
    description: 'Conference highlights and key moments',
    fileName: 'event-highlights.mp4',
    fileSize: 62914560, // 60 MB
    width: 1920,
    height: 1080,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
    uploadDate: '2024-01-11T10:15:00Z',
    tags: ['video', 'event', 'conference', 'highlights'],
    albumId: 'album-video',
    isFavorite: true,
    type: 'video',
    category: 'video',
    client: 'TechConf 2024',
    project: 'Event Coverage',
    likes: 118,
    comments: 26,
    views: 1989,
    downloads: 78,
    shares: 45,
    colorPalette: ['#6366f1', '#8b5cf6', '#ffffff', '#1f2937']
  },
  {
    id: 'img-048',
    title: 'Animation Explainer',
    description: 'Animated explainer video for service',
    fileName: 'service-explainer.mp4',
    fileSize: 31457280, // 30 MB
    width: 1920,
    height: 1080,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=300&fit=crop',
    uploadDate: '2024-01-10T14:50:00Z',
    tags: ['video', 'animation', 'explainer', 'service'],
    albumId: 'album-video',
    isFavorite: false,
    type: 'video',
    category: 'video',
    client: 'Service Provider',
    likes: 86,
    comments: 19,
    views: 1345,
    downloads: 61,
    shares: 29,
    colorPalette: ['#f59e0b', '#3b82f6', '#ffffff', '#1f2937']
  },

  // PHOTOGRAPHY CATEGORY (6 images)
  {
    id: 'img-049',
    title: 'Portrait Photography',
    description: 'Professional headshot for corporate profile',
    fileName: 'corporate-headshot.jpg',
    fileSize: 4194304, // 4 MB
    width: 2400,
    height: 3000,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=750&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=375&fit=crop',
    uploadDate: '2024-01-15T13:30:00Z',
    tags: ['photography', 'portrait', 'headshot', 'professional'],
    albumId: 'album-photo',
    isFavorite: true,
    type: 'image',
    category: 'photography',
    client: 'LinkedIn Profile',
    likes: 72,
    comments: 16,
    views: 467,
    downloads: 36,
    shares: 12,
    metadata: {
      camera: 'Canon EOS R5',
      lens: 'RF 85mm f/1.2',
      iso: 100,
      aperture: 'f/2.8',
      shutterSpeed: '1/200',
      focalLength: '85mm'
    }
  },
  {
    id: 'img-050',
    title: 'Product Photography',
    description: 'High-end product shots for e-commerce',
    fileName: 'product-shots.jpg',
    fileSize: 3670016, // 3.5 MB
    width: 2000,
    height: 2000,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop',
    uploadDate: '2024-01-14T11:15:00Z',
    tags: ['photography', 'product', 'ecommerce', 'commercial'],
    albumId: 'album-photo',
    isFavorite: false,
    type: 'image',
    category: 'photography',
    client: 'Watch Brand',
    project: 'Product Catalog',
    likes: 84,
    comments: 19,
    views: 545,
    downloads: 42,
    shares: 17,
    metadata: {
      camera: 'Sony A7R IV',
      lens: 'FE 90mm f/2.8 Macro',
      iso: 64,
      aperture: 'f/11',
      shutterSpeed: '1/125',
      focalLength: '90mm'
    }
  },
  {
    id: 'img-051',
    title: 'Architecture Photography',
    description: 'Modern building exterior photography',
    fileName: 'architecture-exterior.jpg',
    fileSize: 5242880, // 5 MB
    width: 4000,
    height: 2667,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1486718448742-163732cd1544?w=800&h=533&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1486718448742-163732cd1544?w=400&h=267&fit=crop',
    uploadDate: '2024-01-13T09:45:00Z',
    tags: ['photography', 'architecture', 'building', 'exterior'],
    albumId: 'album-photo',
    isFavorite: true,
    type: 'image',
    category: 'photography',
    client: 'Real Estate Developer',
    likes: 96,
    comments: 22,
    views: 623,
    downloads: 48,
    shares: 21,
    metadata: {
      camera: 'Nikon Z7 II',
      lens: 'Z 14-24mm f/2.8',
      iso: 200,
      aperture: 'f/8',
      shutterSpeed: '1/500',
      focalLength: '14mm'
    }
  },
  {
    id: 'img-052',
    title: 'Food Photography',
    description: 'Gourmet dish styling and photography',
    fileName: 'gourmet-dish.jpg',
    fileSize: 3145728, // 3 MB
    width: 2500,
    height: 1875,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    uploadDate: '2024-01-12T14:20:00Z',
    tags: ['photography', 'food', 'culinary', 'restaurant'],
    albumId: 'album-photo',
    isFavorite: true,
    type: 'image',
    category: 'photography',
    client: 'Fine Dining Restaurant',
    project: 'Menu Photography',
    likes: 128,
    comments: 29,
    views: 834,
    downloads: 64,
    shares: 37,
    metadata: {
      camera: 'Fujifilm X-T4',
      lens: 'XF 56mm f/1.2',
      iso: 400,
      aperture: 'f/2.8',
      shutterSpeed: '1/80',
      focalLength: '56mm'
    }
  },
  {
    id: 'img-053',
    title: 'Landscape Photography',
    description: 'Scenic mountain landscape at golden hour',
    fileName: 'mountain-landscape.jpg',
    fileSize: 6291456, // 6 MB
    width: 5000,
    height: 3333,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=533&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=267&fit=crop',
    uploadDate: '2024-01-11T08:30:00Z',
    tags: ['photography', 'landscape', 'nature', 'mountains'],
    albumId: 'album-photo',
    isFavorite: true,
    type: 'image',
    category: 'photography',
    client: 'Travel Magazine',
    likes: 203,
    comments: 45,
    views: 1324,
    downloads: 98,
    shares: 67,
    metadata: {
      camera: 'Canon EOS 5D Mark IV',
      lens: 'EF 16-35mm f/2.8',
      iso: 100,
      aperture: 'f/11',
      shutterSpeed: '1/250',
      focalLength: '24mm',
      location: 'Swiss Alps'
    }
  },
  {
    id: 'img-054',
    title: 'Event Photography',
    description: 'Corporate event and networking coverage',
    fileName: 'corporate-event.jpg',
    fileSize: 4718592, // 4.5 MB
    width: 3200,
    height: 2133,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=533&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=400&h=267&fit=crop',
    uploadDate: '2024-01-10T16:45:00Z',
    tags: ['photography', 'event', 'corporate', 'networking'],
    albumId: 'album-photo',
    isFavorite: false,
    type: 'image',
    category: 'photography',
    client: 'Business Summit',
    likes: 67,
    comments: 15,
    views: 445,
    downloads: 34,
    shares: 14,
    metadata: {
      camera: 'Sony A9 II',
      lens: 'FE 24-70mm f/2.8',
      iso: 1600,
      aperture: 'f/2.8',
      shutterSpeed: '1/200',
      focalLength: '35mm'
    }
  },

  // ILLUSTRATION CATEGORY (4 images)
  {
    id: 'img-055',
    title: 'Digital Illustration',
    description: 'Character illustration for children book',
    fileName: 'character-illustration.png',
    fileSize: 5242880, // 5 MB
    width: 3000,
    height: 3000,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&h=300&fit=crop',
    uploadDate: '2024-01-15T10:00:00Z',
    tags: ['illustration', 'digital', 'character', 'children'],
    albumId: 'album-illustration',
    isFavorite: true,
    type: 'image',
    category: 'illustration',
    client: 'Publishing House',
    project: 'Children Book Series',
    likes: 134,
    comments: 31,
    views: 876,
    downloads: 67,
    shares: 43,
    colorPalette: ['#fbbf24', '#ec4899', '#10b981', '#ffffff']
  },
  {
    id: 'img-056',
    title: 'Infographic Design',
    description: 'Data visualization infographic',
    fileName: 'data-infographic.svg',
    fileSize: 1048576, // 1 MB
    width: 1200,
    height: 3000,
    format: 'svg',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=1000&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=500&fit=crop',
    uploadDate: '2024-01-14T13:25:00Z',
    tags: ['illustration', 'infographic', 'data', 'visualization'],
    albumId: 'album-illustration',
    isFavorite: false,
    type: 'image',
    category: 'illustration',
    client: 'Research Firm',
    likes: 89,
    comments: 20,
    views: 578,
    downloads: 45,
    shares: 28,
    colorPalette: ['#3b82f6', '#8b5cf6', '#10b981', '#f59e0b']
  },
  {
    id: 'img-057',
    title: 'Icon Set Design',
    description: 'Custom icon pack for application',
    fileName: 'icon-set.svg',
    fileSize: 524288, // 512 KB
    width: 2400,
    height: 2400,
    format: 'svg',
    url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=300&h=300&fit=crop',
    uploadDate: '2024-01-13T15:40:00Z',
    tags: ['illustration', 'icons', 'UI', 'design-system'],
    albumId: 'album-illustration',
    isFavorite: true,
    type: 'image',
    category: 'illustration',
    client: 'SaaS Application',
    project: 'Design System',
    likes: 112,
    comments: 25,
    views: 723,
    downloads: 56,
    shares: 34,
    colorPalette: ['#1f2937', '#3b82f6', '#ffffff']
  },
  {
    id: 'img-058',
    title: 'Editorial Illustration',
    description: 'Magazine article illustration',
    fileName: 'editorial-illustration.jpg',
    fileSize: 2621440, // 2.5 MB
    width: 2000,
    height: 2667,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=800&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=300&h=400&fit=crop',
    uploadDate: '2024-01-12T11:10:00Z',
    tags: ['illustration', 'editorial', 'magazine', 'art'],
    albumId: 'album-illustration',
    isFavorite: false,
    type: 'image',
    category: 'illustration',
    client: 'Editorial Magazine',
    likes: 76,
    comments: 17,
    views: 489,
    downloads: 38,
    shares: 19,
    colorPalette: ['#ec4899', '#8b5cf6', '#fbbf24', '#1f2937']
  },

  // 3D & ANIMATION CATEGORY (4 images)
  {
    id: 'img-059',
    title: '3D Product Render',
    description: 'Photorealistic 3D product visualization',
    fileName: '3d-product-render.png',
    fileSize: 6291456, // 6 MB
    width: 4000,
    height: 4000,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop',
    uploadDate: '2024-01-15T15:20:00Z',
    tags: ['3D', 'render', 'product', 'visualization'],
    albumId: 'album-3d',
    isFavorite: true,
    type: 'image',
    category: '3d',
    client: 'Product Design Studio',
    project: '3D Visualization',
    likes: 147,
    comments: 33,
    views: 956,
    downloads: 73,
    shares: 48,
    colorPalette: ['#1f2937', '#ffffff', '#3b82f6']
  },
  {
    id: 'img-060',
    title: 'Motion Graphics',
    description: 'Animated logo reveal sequence',
    fileName: 'logo-animation.mp4',
    fileSize: 15728640, // 15 MB
    width: 1920,
    height: 1080,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop',
    uploadDate: '2024-01-14T12:15:00Z',
    tags: ['animation', 'motion-graphics', 'logo', 'video'],
    albumId: 'album-3d',
    isFavorite: true,
    type: 'video',
    category: 'animation',
    client: 'Tech Startup',
    likes: 93,
    comments: 21,
    views: 612,
    downloads: 47,
    shares: 26,
    colorPalette: ['#8b5cf6', '#ffffff', '#1f2937']
  },
  {
    id: 'img-061',
    title: 'Architectural Visualization',
    description: '3D interior design rendering',
    fileName: 'interior-render.jpg',
    fileSize: 7340032, // 7 MB
    width: 4500,
    height: 3000,
    format: 'jpg',
    url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&h=533&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400&h=267&fit=crop',
    uploadDate: '2024-01-13T10:50:00Z',
    tags: ['3D', 'architecture', 'interior', 'visualization'],
    albumId: 'album-3d',
    isFavorite: false,
    type: 'image',
    category: '3d',
    client: 'Architecture Firm',
    project: 'Residential Complex',
    likes: 108,
    comments: 24,
    views: 701,
    downloads: 54,
    shares: 31,
    colorPalette: ['#fef3c7', '#92400e', '#1f2937', '#ffffff']
  },
  {
    id: 'img-062',
    title: 'Character Animation',
    description: 'Animated character for game project',
    fileName: 'character-animation.mp4',
    fileSize: 20971520, // 20 MB
    width: 1280,
    height: 720,
    format: 'mp4',
    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=300&fit=crop',
    uploadDate: '2024-01-12T16:35:00Z',
    tags: ['animation', '3D', 'character', 'game'],
    albumId: 'album-3d',
    isFavorite: true,
    type: 'video',
    category: 'animation',
    client: 'Game Developer',
    likes: 156,
    comments: 35,
    views: 1012,
    downloads: 78,
    shares: 52,
    colorPalette: ['#10b981', '#fbbf24', '#1f2937']
  },

  // AI-GENERATED CATEGORY (2 images)
  {
    id: 'img-063',
    title: 'AI Generated Landscape',
    description: 'Surreal landscape created with AI',
    fileName: 'ai-landscape.png',
    fileSize: 4194304, // 4 MB
    width: 2048,
    height: 2048,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=300&fit=crop',
    uploadDate: '2024-01-15T16:00:00Z',
    tags: ['AI', 'generated', 'landscape', 'surreal'],
    albumId: null,
    isFavorite: true,
    type: 'image',
    category: 'ai-generated',
    likes: 189,
    comments: 42,
    views: 1234,
    downloads: 95,
    shares: 67,
    aiGenerated: true,
    sourcePrompt: 'Surreal landscape with floating islands, vibrant colors, digital art style',
    colorPalette: ['#8b5cf6', '#ec4899', '#fbbf24', '#10b981']
  },
  {
    id: 'img-064',
    title: 'AI Portrait Art',
    description: 'Artistic portrait generated with AI',
    fileName: 'ai-portrait.png',
    fileSize: 3670016, // 3.5 MB
    width: 2048,
    height: 2048,
    format: 'png',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    uploadDate: '2024-01-14T14:30:00Z',
    tags: ['AI', 'generated', 'portrait', 'art'],
    albumId: null,
    isFavorite: true,
    type: 'image',
    category: 'ai-generated',
    likes: 167,
    comments: 38,
    views: 1089,
    downloads: 84,
    shares: 59,
    aiGenerated: true,
    sourcePrompt: 'Portrait of a futuristic cyberpunk character, neon lights, detailed face, cinematic',
    colorPalette: ['#06b6d4', '#ec4899', '#1f2937', '#ffffff']
  }
]

// ================================
// MOCK DATA - ALBUMS
// ================================

export const mockAlbums: Album[] = [
  {
    id: 'album-brand',
    name: 'Brand Identity Projects',
    description: 'Complete brand identity packages and logo designs',
    coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop',
    imageCount: 10,
    createdDate: '2024-01-15T10:00:00Z',
    modifiedDate: '2024-01-15T17:30:00Z',
    totalSize: 24117248, // Sum of branding images
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/brand-identity-2024',
    tags: ['branding', 'logo', 'identity'],
    views: 234,
    downloads: 45
  },
  {
    id: 'album-web',
    name: 'Web Design Portfolio',
    description: 'Website designs and UI/UX projects',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    imageCount: 10,
    createdDate: '2024-01-14T09:00:00Z',
    modifiedDate: '2024-01-15T16:50:00Z',
    totalSize: 43253760,
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/web-design-2024',
    tags: ['web-design', 'UI', 'UX'],
    views: 456,
    downloads: 78
  },
  {
    id: 'album-mobile',
    name: 'Mobile App Designs',
    description: 'iOS and Android app interface designs',
    coverImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=600&fit=crop',
    imageCount: 8,
    createdDate: '2024-01-13T11:00:00Z',
    modifiedDate: '2024-01-15T16:35:00Z',
    totalSize: 17301504,
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/mobile-apps-2024',
    tags: ['mobile', 'app-design', 'iOS', 'Android'],
    views: 389,
    downloads: 62
  },
  {
    id: 'album-social',
    name: 'Social Media Graphics',
    description: 'Social media content and campaigns',
    coverImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=400&fit=crop',
    imageCount: 8,
    createdDate: '2024-01-12T10:00:00Z',
    modifiedDate: '2024-01-15T13:50:00Z',
    totalSize: 12845056,
    isPublic: false,
    tags: ['social-media', 'marketing', 'campaigns'],
    views: 567,
    downloads: 89
  },
  {
    id: 'album-print',
    name: 'Print Design Collection',
    description: 'Brochures, flyers, and print materials',
    coverImage: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?w=400&h=300&fit=crop',
    imageCount: 6,
    createdDate: '2024-01-11T14:00:00Z',
    modifiedDate: '2024-01-15T10:25:00Z',
    totalSize: 29884416,
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/print-design-2024',
    tags: ['print', 'brochure', 'marketing'],
    views: 198,
    downloads: 34
  },
  {
    id: 'album-video',
    name: 'Video Productions',
    description: 'Commercial videos and motion graphics',
    coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    imageCount: 6,
    createdDate: '2024-01-10T13:00:00Z',
    modifiedDate: '2024-01-15T14:50:00Z',
    totalSize: 277872640,
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/video-portfolio-2024',
    tags: ['video', 'motion-graphics', 'commercial'],
    views: 723,
    downloads: 123
  },
  {
    id: 'album-photo',
    name: 'Photography Portfolio',
    description: 'Professional photography work',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    imageCount: 6,
    createdDate: '2024-01-09T12:00:00Z',
    modifiedDate: '2024-01-15T16:45:00Z',
    totalSize: 28181504,
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/photography-2024',
    tags: ['photography', 'portrait', 'commercial'],
    views: 891,
    downloads: 145
  },
  {
    id: 'album-illustration',
    name: 'Illustrations & Icons',
    description: 'Digital illustrations and icon designs',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=300&fit=crop',
    imageCount: 4,
    createdDate: '2024-01-08T15:00:00Z',
    modifiedDate: '2024-01-15T15:40:00Z',
    totalSize: 9437184,
    isPublic: false,
    tags: ['illustration', 'icons', 'digital-art'],
    views: 412,
    downloads: 67
  },
  {
    id: 'album-3d',
    name: '3D & Animation',
    description: '3D renders and animated content',
    coverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop',
    imageCount: 4,
    createdDate: '2024-01-07T11:00:00Z',
    modifiedDate: '2024-01-15T16:35:00Z',
    totalSize: 50331648,
    isPublic: true,
    shareUrl: 'https://gallery.kazi.com/albums/3d-animation-2024',
    tags: ['3D', 'animation', 'visualization'],
    views: 645,
    downloads: 98
  },
  {
    id: 'album-client-work',
    name: 'Client Projects 2024',
    description: 'Completed client projects and deliverables',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    imageCount: 25,
    createdDate: '2024-01-01T00:00:00Z',
    modifiedDate: '2024-01-15T17:00:00Z',
    totalSize: 157286400,
    isPublic: false,
    password: 'client2024',
    tags: ['client-work', 'projects', 'deliverables'],
    views: 1234,
    downloads: 234
  }
]

// ================================
// MOCK DATA - TAGS
// ================================

export const mockImageTags: ImageTag[] = [
  { id: 'tag-001', name: 'branding', color: '#3b82f6', category: 'Design', usageCount: 15, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-002', name: 'logo', color: '#8b5cf6', category: 'Design', usageCount: 12, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-003', name: 'web-design', color: '#10b981', category: 'Design', usageCount: 18, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-004', name: 'mobile', color: '#f59e0b', category: 'Design', usageCount: 14, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-005', name: 'social-media', color: '#ec4899', category: 'Marketing', usageCount: 11, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-006', name: 'photography', color: '#06b6d4', category: 'Media', usageCount: 9, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-007', name: 'illustration', color: '#8b5cf6', category: 'Art', usageCount: 7, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-008', name: '3D', color: '#1e40af', category: 'Media', usageCount: 6, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-009', name: 'video', color: '#dc2626', category: 'Media', usageCount: 10, createdDate: '2024-01-01T00:00:00Z' },
  { id: 'tag-010', name: 'print', color: '#7c2d12', category: 'Design', usageCount: 8, createdDate: '2024-01-01T00:00:00Z' }
]

// ================================
// MOCK DATA - COLLECTIONS
// ================================

export const mockCollections: ImageCollection[] = [
  {
    id: 'collection-featured',
    name: 'Featured Work',
    description: 'Best work to showcase to clients',
    imageIds: ['img-001', 'img-003', 'img-011', 'img-015', 'img-021', 'img-029', 'img-043', 'img-055', 'img-063'],
    createdBy: 'user-001',
    createdDate: '2024-01-01T00:00:00Z',
    isAutoGenerated: false
  },
  {
    id: 'collection-recent',
    name: 'Recent Uploads',
    description: 'Images uploaded in the last 7 days',
    imageIds: ['img-001', 'img-011', 'img-021', 'img-029', 'img-043', 'img-049', 'img-055', 'img-059', 'img-063'],
    createdBy: 'system',
    createdDate: '2024-01-15T00:00:00Z',
    isAutoGenerated: true,
    rules: [
      { field: 'uploadDate', operator: 'greater_than', value: '7 days ago' }
    ]
  },
  {
    id: 'collection-popular',
    name: 'Most Popular',
    description: 'Images with highest engagement',
    imageIds: ['img-063', 'img-064', 'img-051', 'img-029', 'img-043'],
    createdBy: 'system',
    createdDate: '2024-01-10T00:00:00Z',
    isAutoGenerated: true,
    rules: [
      { field: 'views', operator: 'greater_than', value: 1000 }
    ]
  },
  {
    id: 'collection-client-ready',
    name: 'Client Ready',
    description: 'Polished work ready for client presentation',
    imageIds: ['img-001', 'img-002', 'img-011', 'img-012', 'img-021', 'img-037', 'img-043', 'img-049'],
    createdBy: 'user-001',
    createdDate: '2024-01-05T00:00:00Z'
  }
]

// ================================
// HELPER FUNCTIONS
// ================================

/**
 * Format file size from bytes to human-readable string
 */
export const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 B'
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)} GB`
}

/**
 * Format date to readable string
 */
export const formatDate = (isoDate: string): string => {
  return new Date(isoDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

/**
 * Format date with time
 */
export const formatDateTime = (isoDate: string): string => {
  return new Date(isoDate).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

/**
 * Get time ago string
 */
export const getTimeAgo = (isoDate: string): string => {
  const now = new Date()
  const then = new Date(isoDate)
  const diffMs = now.getTime() - then.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)

  if (diffMins < 1) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays < 7) return `${diffDays}d ago`
  if (diffDays < 30) return `${Math.floor(diffDays / 7)}w ago`
  if (diffDays < 365) return `${Math.floor(diffDays / 30)}mo ago`
  return `${Math.floor(diffDays / 365)}y ago`
}

/**
 * Calculate total storage used
 */
export const calculateTotalStorage = (images: GalleryImage[]): number => {
  return images.reduce((total, img) => total + img.fileSize, 0)
}

/**
 * Get storage by category
 */
export const getStorageByCategory = (images: GalleryImage[]): Record<string, number> => {
  const storage: Record<string, number> = {}

  images.forEach(img => {
    if (!storage[img.category]) {
      storage[img.category] = 0
    }
    storage[img.category] += img.fileSize
  })

  return storage
}

/**
 * Filter images
 */
export const filterImages = (images: GalleryImage[], filter: ImageFilter): GalleryImage[] => {
  return images.filter(img => {
    // Category filter
    if (filter.categories && filter.categories.length > 0) {
      if (!filter.categories.includes(img.category)) return false
    }

    // Type filter
    if (filter.types && filter.types.length > 0) {
      if (!filter.types.includes(img.type)) return false
    }

    // Tags filter
    if (filter.tags && filter.tags.length > 0) {
      if (!filter.tags.some(tag => img.tags.includes(tag))) return false
    }

    // Album filter
    if (filter.albumIds && filter.albumIds.length > 0) {
      if (!img.albumId || !filter.albumIds.includes(img.albumId)) return false
    }

    // Favorite filter
    if (filter.isFavorite !== undefined) {
      if (img.isFavorite !== filter.isFavorite) return false
    }

    // Public filter
    if (filter.isPublic !== undefined) {
      if (img.isPublic !== filter.isPublic) return false
    }

    // AI generated filter
    if (filter.aiGenerated !== undefined) {
      if (img.aiGenerated !== filter.aiGenerated) return false
    }

    // Date range filter
    if (filter.dateRange) {
      const uploadDate = new Date(img.uploadDate)
      const startDate = new Date(filter.dateRange.start)
      const endDate = new Date(filter.dateRange.end)
      if (uploadDate < startDate || uploadDate > endDate) return false
    }

    // Size filters
    if (filter.minSize && img.fileSize < filter.minSize) return false
    if (filter.maxSize && img.fileSize > filter.maxSize) return false

    // Dimension filters
    if (filter.minDimensions) {
      if (img.width < filter.minDimensions.width || img.height < filter.minDimensions.height) return false
    }
    if (filter.maxDimensions) {
      if (img.width > filter.maxDimensions.width || img.height > filter.maxDimensions.height) return false
    }

    return true
  })
}

/**
 * Sort images
 */
export const sortImages = (images: GalleryImage[], field: SortField, order: SortOrder): GalleryImage[] => {
  const sorted = [...images].sort((a, b) => {
    let comparison = 0

    switch (field) {
      case 'date':
        comparison = new Date(b.uploadDate).getTime() - new Date(a.uploadDate).getTime()
        break
      case 'name':
        comparison = a.title.localeCompare(b.title)
        break
      case 'size':
        comparison = b.fileSize - a.fileSize
        break
      case 'type':
        comparison = a.type.localeCompare(b.type)
        break
      case 'views':
        comparison = b.views - a.views
        break
      case 'likes':
        comparison = b.likes - a.likes
        break
      case 'downloads':
        comparison = b.downloads - a.downloads
        break
    }

    return order === 'asc' ? -comparison : comparison
  })

  return sorted
}

/**
 * Search images
 */
export const searchImages = (images: GalleryImage[], query: string): GalleryImage[] => {
  const lowerQuery = query.toLowerCase()

  return images.filter(img => {
    return (
      img.title.toLowerCase().includes(lowerQuery) ||
      img.description.toLowerCase().includes(lowerQuery) ||
      img.fileName.toLowerCase().includes(lowerQuery) ||
      img.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
      img.category.toLowerCase().includes(lowerQuery) ||
      img.client?.toLowerCase().includes(lowerQuery) ||
      img.project?.toLowerCase().includes(lowerQuery)
    )
  })
}

/**
 * Get top images by metric
 */
export const getTopImages = (images: GalleryImage[], metric: 'views' | 'likes' | 'downloads', limit: number = 10): GalleryImage[] => {
  return [...images]
    .sort((a, b) => b[metric] - a[metric])
    .slice(0, limit)
}

/**
 * Get images by album
 */
export const getImagesByAlbum = (images: GalleryImage[], albumId: string): GalleryImage[] => {
  return images.filter(img => img.albumId === albumId)
}

/**
 * Get favorite images
 */
export const getFavoriteImages = (images: GalleryImage[]): GalleryImage[] => {
  return images.filter(img => img.isFavorite)
}

/**
 * Get recent images
 */
export const getRecentImages = (images: GalleryImage[], days: number = 7): GalleryImage[] => {
  const cutoffDate = new Date()
  cutoffDate.setDate(cutoffDate.getDate() - days)

  return images.filter(img => new Date(img.uploadDate) >= cutoffDate)
}

/**
 * Get images by tag
 */
export const getImagesByTag = (images: GalleryImage[], tag: string): GalleryImage[] => {
  return images.filter(img => img.tags.includes(tag))
}

/**
 * Get images by category
 */
export const getImagesByCategory = (images: GalleryImage[], category: string): GalleryImage[] => {
  return images.filter(img => img.category === category)
}

/**
 * Get images by type
 */
export const getImagesByType = (images: GalleryImage[], type: 'image' | 'video' | 'audio' | 'document'): GalleryImage[] => {
  return images.filter(img => img.type === type)
}

/**
 * Get all unique tags from images
 */
export const getAllTags = (images: GalleryImage[]): string[] => {
  const tags = new Set<string>()
  images.forEach(img => {
    img.tags.forEach(tag => tags.add(tag))
  })
  return Array.from(tags).sort()
}

/**
 * Get all unique categories
 */
export const getAllCategories = (images: GalleryImage[]): string[] => {
  const categories = new Set<string>()
  images.forEach(img => categories.add(img.category))
  return Array.from(categories).sort()
}

/**
 * Calculate gallery analytics
 */
export const calculateGalleryAnalytics = (images: GalleryImage[], albums: Album[]): GalleryAnalytics => {
  const totalImages = images.filter(img => img.type === 'image').length
  const totalVideos = images.filter(img => img.type === 'video').length
  const totalAlbums = albums.length
  const totalStorage = calculateTotalStorage(images)
  const totalViews = images.reduce((sum, img) => sum + img.views, 0)
  const totalDownloads = images.reduce((sum, img) => sum + img.downloads, 0)
  const totalLikes = images.reduce((sum, img) => sum + img.likes, 0)
  const totalComments = images.reduce((sum, img) => sum + img.comments, 0)

  const topImages = getTopImages(images, 'views', 5)
  const topAlbums = [...albums].sort((a, b) => (b.views || 0) - (a.views || 0)).slice(0, 5)
  const recentUploads = getRecentImages(images, 7).slice(0, 10)
  const storageByCategory = getStorageByCategory(images)

  // Mock views by day
  const viewsByDay = Array.from({ length: 30 }, (_, i) => {
    const date = new Date()
    date.setDate(date.getDate() - (29 - i))
    return {
      date: date.toISOString().split('T')[0],
      views: Math.floor(Math.random() * 200) + 50
    }
  })

  return {
    totalImages,
    totalVideos,
    totalAlbums,
    totalStorage,
    totalViews,
    totalDownloads,
    totalLikes,
    totalComments,
    topImages,
    topAlbums,
    recentUploads,
    storageByCategory,
    viewsByDay
  }
}

/**
 * Export images as JSON
 */
export const exportImagesAsJSON = (images: GalleryImage[]): string => {
  return JSON.stringify(images, null, 2)
}

/**
 * Export gallery statistics
 */
export const exportGalleryStats = (images: GalleryImage[], albums: Album[]): string => {
  const analytics = calculateGalleryAnalytics(images, albums)

  const stats = {
    summary: {
      totalImages: analytics.totalImages,
      totalVideos: analytics.totalVideos,
      totalAlbums: analytics.totalAlbums,
      totalStorage: formatFileSize(analytics.totalStorage),
      totalViews: analytics.totalViews,
      totalDownloads: analytics.totalDownloads,
      totalLikes: analytics.totalLikes,
      totalComments: analytics.totalComments
    },
    topImages: analytics.topImages.map(img => ({
      title: img.title,
      views: img.views,
      likes: img.likes,
      downloads: img.downloads
    })),
    categories: analytics.storageByCategory,
    generated: new Date().toISOString()
  }

  return JSON.stringify(stats, null, 2)
}

/**
 * Generate share URL
 */
export const generateShareUrl = (imageId: string, baseUrl: string = 'https://gallery.kazi.com'): string => {
  return `${baseUrl}/share/${imageId}`
}

/**
 * Generate album share URL
 */
export const generateAlbumShareUrl = (albumId: string, baseUrl: string = 'https://gallery.kazi.com'): string => {
  return `${baseUrl}/albums/${albumId}`
}

/**
 * Extract dominant colors from image (mock implementation)
 */
export const extractColorPalette = async (imageUrl: string): Promise<string[]> => {
  // In production, this would use a color extraction library
  // Mock implementation returns random colors
  logger.info('Extracting color palette', { imageUrl })

  await new Promise(resolve => setTimeout(resolve, 500))

  return [
    '#' + Math.floor(Math.random() * 16777215).toString(16),
    '#' + Math.floor(Math.random() * 16777215).toString(16),
    '#' + Math.floor(Math.random() * 16777215).toString(16),
    '#' + Math.floor(Math.random() * 16777215).toString(16)
  ]
}

/**
 * Find similar images (mock implementation)
 */
export const findSimilarImages = (targetImage: GalleryImage, allImages: GalleryImage[], limit: number = 5): GalleryImage[] => {
  logger.info('Finding similar images', { targetImageId: targetImage.id, limit })

  // In production, this would use image similarity algorithms
  // Mock: find images with matching tags or category
  const similar = allImages
    .filter(img => img.id !== targetImage.id)
    .filter(img => {
      const matchingTags = img.tags.filter(tag => targetImage.tags.includes(tag)).length
      const sameCategory = img.category === targetImage.category
      return matchingTags > 0 || sameCategory
    })
    .sort((a, b) => {
      const aMatchingTags = a.tags.filter(tag => targetImage.tags.includes(tag)).length
      const bMatchingTags = b.tags.filter(tag => targetImage.tags.includes(tag)).length
      return bMatchingTags - aMatchingTags
    })
    .slice(0, limit)

  return similar
}

/**
 * Auto-tag image using AI (mock implementation)
 */
export const autoTagImage = async (imageUrl: string): Promise<string[]> => {
  logger.info('Auto-tagging image with AI', { imageUrl })

  // In production, this would use AI image recognition
  // Mock implementation returns sample tags
  await new Promise(resolve => setTimeout(resolve, 1000))

  const possibleTags = [
    'nature', 'landscape', 'portrait', 'architecture', 'food',
    'technology', 'business', 'abstract', 'creative', 'minimalist',
    'colorful', 'black-and-white', 'vintage', 'modern', 'professional'
  ]

  const numTags = Math.floor(Math.random() * 5) + 3
  const tags: string[] = []

  for (let i = 0; i < numTags; i++) {
    const tag = possibleTags[Math.floor(Math.random() * possibleTags.length)]
    if (!tags.includes(tag)) {
      tags.push(tag)
    }
  }

  return tags
}

/**
 * Validate image file
 */
export const validateImageFile = (file: File): { valid: boolean; error?: string } => {
  const maxSize = 50 * 1024 * 1024 // 50 MB
  const allowedFormats = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml', 'video/mp4', 'video/mov']

  if (file.size > maxSize) {
    return { valid: false, error: `File size exceeds 50 MB limit (${formatFileSize(file.size)})` }
  }

  if (!allowedFormats.includes(file.type)) {
    return { valid: false, error: `Unsupported file format: ${file.type}` }
  }

  return { valid: true }
}

/**
 * Generate thumbnail URL (mock)
 */
export const generateThumbnailUrl = (originalUrl: string, width: number = 400, height: number = 300): string => {
  // In production, this would use an image processing service
  return `${originalUrl}?w=${width}&h=${height}&fit=crop`
}

/**
 * Bulk update images
 */
export const bulkUpdateImages = (
  images: GalleryImage[],
  imageIds: string[],
  updates: Partial<GalleryImage>
): GalleryImage[] => {
  logger.info('Bulk updating images', { imageCount: imageIds.length, updates })

  return images.map(img => {
    if (imageIds.includes(img.id)) {
      return { ...img, ...updates, modifiedDate: new Date().toISOString() }
    }
    return img
  })
}

/**
 * Bulk delete images
 */
export const bulkDeleteImages = (images: GalleryImage[], imageIds: string[]): GalleryImage[] => {
  logger.info('Bulk deleting images', { imageCount: imageIds.length })

  return images.filter(img => !imageIds.includes(img.id))
}

/**
 * Move images to album
 */
export const moveImagesToAlbum = (
  images: GalleryImage[],
  imageIds: string[],
  targetAlbumId: string | null
): GalleryImage[] => {
  logger.info('Moving images to album', { imageCount: imageIds.length, targetAlbumId })

  return images.map(img => {
    if (imageIds.includes(img.id)) {
      return { ...img, albumId: targetAlbumId, modifiedDate: new Date().toISOString() }
    }
    return img
  })
}

/**
 * Add tags to images
 */
export const addTagsToImages = (
  images: GalleryImage[],
  imageIds: string[],
  newTags: string[]
): GalleryImage[] => {
  logger.info('Adding tags to images', { imageCount: imageIds.length, tagCount: newTags.length })

  return images.map(img => {
    if (imageIds.includes(img.id)) {
      const uniqueTags = Array.from(new Set([...img.tags, ...newTags]))
      return { ...img, tags: uniqueTags, modifiedDate: new Date().toISOString() }
    }
    return img
  })
}

/**
 * Remove tags from images
 */
export const removeTagsFromImages = (
  images: GalleryImage[],
  imageIds: string[],
  tagsToRemove: string[]
): GalleryImage[] => {
  logger.info('Removing tags from images', { imageCount: imageIds.length, tagCount: tagsToRemove.length })

  return images.map(img => {
    if (imageIds.includes(img.id)) {
      const tags = img.tags.filter(tag => !tagsToRemove.includes(tag))
      return { ...img, tags, modifiedDate: new Date().toISOString() }
    }
    return img
  })
}

logger.info('Gallery utilities loaded', {
  mockImagesCount: mockGalleryImages.length,
  mockAlbumsCount: mockAlbums.length,
  mockTagsCount: mockImageTags.length,
  mockCollectionsCount: mockCollections.length
})
